[22-May-22 18:47:22 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:47:25 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:47:26 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 19:01:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 19:01:06 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 11:38:22 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 11:38:22 - INFO] - root - ### Processing: Venom client ###
[23-May-22 11:38:22 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 11:38:31 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 11:38:33 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 11:38:33 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 11:40:23 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 11:40:23 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 11:41:30 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 11:41:30 - INFO] - root - ### Processing: Venom client ###
[23-May-22 11:41:30 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 11:41:38 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 11:41:40 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 11:41:40 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 11:49:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 11:49:43 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 11:49:48 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 11:49:48 - INFO] - root - ### Processing: Venom client ###
[23-May-22 11:49:48 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 11:49:57 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 11:49:59 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 11:49:59 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 12:20:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 12:20:05 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 12:39:44 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 12:39:44 - INFO] - root - ### Processing: Venom client ###
[23-May-22 12:39:44 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 12:39:54 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 12:39:56 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 12:39:57 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 12:41:44 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 12:41:44 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 12:56:39 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 12:56:39 - INFO] - root - ### Processing: Venom client ###
[23-May-22 12:56:39 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 12:56:49 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 12:56:51 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 12:56:51 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 12:57:11 - ERROR] - pyrogram.dispatcher - 'InlineQueryResultPhoto' object is not iterable
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\plugins\fun\alive.py", line 127, in alive_media_inline
    await i_q.answer(results=results[-1])
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\types\inline_mode\inline_query.py", line 172, in answer
    return await self._client.answer_inline_query(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\bots\answer_inline_query.py", line 100, in answer_inline_query
    results=[await r.write(self) for r in results],
TypeError: 'InlineQueryResultPhoto' object is not iterable
[23-May-22 12:57:48 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 12:57:48 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 12:57:51 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 12:57:51 - INFO] - root - ### Processing: Venom client ###
[23-May-22 12:57:51 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 12:58:00 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 12:58:02 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 12:58:02 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 12:59:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 12:59:04 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 12:59:16 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 12:59:16 - INFO] - root - ### Processing: Venom client ###
[23-May-22 12:59:16 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 12:59:25 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 12:59:27 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 12:59:28 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 12:59:56 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 12:59:57 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 13:00:55 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 13:00:56 - INFO] - root - ### Processing: Venom client ###
[23-May-22 13:00:56 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 13:01:04 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:01:07 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:01:07 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 13:01:55 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: timed out
[23-May-22 13:07:37 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 13:07:38 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 13:20:24 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 13:20:24 - INFO] - root - ### Processing: Venom client ###
[23-May-22 13:20:24 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 13:20:34 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:20:36 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:20:36 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 13:23:44 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\plugins\fun\alive.py", line 151, in alive_media_inline
    await i_q.answer(results=results, cache_time=1)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\types\inline_mode\inline_query.py", line 172, in answer
    return await self._client.answer_inline_query(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\bots\answer_inline_query.py", line 97, in answer_inline_query
    return await self.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 360, in invoke
    return await self.send(query, timeout=timeout)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 291, in send
    message = self.msg_factory(data)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\functions\messages\set_inline_bot_results.py", line 98, in write
    b.write(Vector(self.results))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_result.py", line 117, in write
    b.write(self.send_message.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_message_media_auto.py", line 84, in write
    b.write(self.reply_markup.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 66, in write
    b.write(Vector(self.rows))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 66, in write
    b.write(Vector(self.buttons))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
AttributeError: 'NoneType' object has no attribute 'write'
[23-May-22 13:23:48 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\plugins\fun\alive.py", line 151, in alive_media_inline
    await i_q.answer(results=results, cache_time=1)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\types\inline_mode\inline_query.py", line 172, in answer
    return await self._client.answer_inline_query(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\bots\answer_inline_query.py", line 97, in answer_inline_query
    return await self.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 360, in invoke
    return await self.send(query, timeout=timeout)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 291, in send
    message = self.msg_factory(data)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\functions\messages\set_inline_bot_results.py", line 98, in write
    b.write(Vector(self.results))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_result.py", line 117, in write
    b.write(self.send_message.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_message_media_auto.py", line 84, in write
    b.write(self.reply_markup.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 66, in write
    b.write(Vector(self.rows))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 66, in write
    b.write(Vector(self.buttons))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
AttributeError: 'NoneType' object has no attribute 'write'
[23-May-22 13:23:54 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 13:23:54 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 13:25:29 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 13:25:29 - INFO] - root - ### Processing: Venom client ###
[23-May-22 13:25:29 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 13:25:38 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:25:40 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:25:40 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 13:25:50 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\plugins\fun\alive.py", line 151, in alive_media_inline
    await i_q.answer(results=results, cache_time=1)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\types\inline_mode\inline_query.py", line 172, in answer
    return await self._client.answer_inline_query(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\bots\answer_inline_query.py", line 97, in answer_inline_query
    return await self.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 360, in invoke
    return await self.send(query, timeout=timeout)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 291, in send
    message = self.msg_factory(data)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\functions\messages\set_inline_bot_results.py", line 98, in write
    b.write(Vector(self.results))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_result.py", line 117, in write
    b.write(self.send_message.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_message_media_auto.py", line 84, in write
    b.write(self.reply_markup.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 66, in write
    b.write(Vector(self.rows))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 66, in write
    b.write(Vector(self.buttons))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
AttributeError: 'NoneType' object has no attribute 'write'
[23-May-22 13:27:08 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 13:27:08 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 13:27:12 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 13:27:12 - INFO] - root - ### Processing: Venom client ###
[23-May-22 13:27:12 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 13:27:21 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
