[22-May-22 18:08:19 - ERROR] - pyrogram.dispatcher - MyMessage.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\Apps\Python\Python310\lib\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
TypeError: MyMessage.__init__() takes 1 positional argument but 2 were given
[22-May-22 18:09:37 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:09:37 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:09:41 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:09:41 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:09:41 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:09:52 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:09:56 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:09:57 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:14:43 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:14:43 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:14:54 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:14:54 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:14:54 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:15:06 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:15:09 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:15:10 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:15:24 - ERROR] - pyrogram.dispatcher - Message.__init__() missing 1 required keyword-only argument: 'id'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__()
TypeError: Message.__init__() missing 1 required keyword-only argument: 'id'
[22-May-22 18:15:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:15:43 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:15:46 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:15:46 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:15:46 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:15:58 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:16:01 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:16:02 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:16:08 - ERROR] - pyrogram.dispatcher - Message.__init__() missing 1 required keyword-only argument: 'id'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 31, in __init__
    super().__init__()
TypeError: Message.__init__() missing 1 required keyword-only argument: 'id'
[22-May-22 18:16:34 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:16:35 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:16:39 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:16:39 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:16:39 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:16:51 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:16:55 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:16:56 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:17:01 - ERROR] - pyrogram.dispatcher - Message.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__(message)
TypeError: Message.__init__() takes 1 positional argument but 2 were given
[22-May-22 18:23:55 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:23:55 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:24:00 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:24:00 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:24:00 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:24:08 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:24:11 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:24:11 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:24:24 - ERROR] - pyrogram.dispatcher - Message.__init__() got multiple values for argument 'self'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__(self=message)
TypeError: Message.__init__() got multiple values for argument 'self'
[22-May-22 18:31:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:31:16 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:31:57 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:31:57 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:31:57 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:32:09 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:32:11 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:32:12 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:32:32 - ERROR] - pyrogram.dispatcher - Message.__init__() got multiple values for argument 'self'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__(self=message)
TypeError: Message.__init__() got multiple values for argument 'self'
[22-May-22 18:32:50 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:32:51 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:33:01 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:33:01 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:33:01 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:33:13 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:33:17 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:33:17 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:34:17 - ERROR] - pyrogram.dispatcher - Message.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__(message)
TypeError: Message.__init__() takes 1 positional argument but 2 were given
[22-May-22 18:34:57 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:34:57 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:35:03 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:35:03 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:35:03 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:35:13 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:35:16 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:35:16 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:35:19 - ERROR] - pyrogram.dispatcher - MyMessage.__init__() missing 1 required positional argument: 'message'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
TypeError: MyMessage.__init__() missing 1 required positional argument: 'message'
[22-May-22 18:36:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:36:00 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:36:31 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:36:31 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:36:31 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:36:42 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:36:45 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:36:46 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:37:02 - ERROR] - pyrogram.dispatcher - Message.__init__() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rc, rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__(client, message)
TypeError: Message.__init__() takes 1 positional argument but 3 were given
[22-May-22 18:37:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:37:43 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:37:47 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:37:47 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:37:47 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:37:58 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:38:01 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:38:02 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:38:12 - ERROR] - pyrogram.dispatcher - Message.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__(self)
TypeError: Message.__init__() takes 1 positional argument but 2 were given
[22-May-22 18:38:47 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:38:48 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:38:52 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:38:52 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:38:52 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:39:02 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:39:05 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:39:06 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:40:53 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:40:54 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:40:58 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:40:58 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:40:58 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:41:08 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:41:11 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:41:12 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:41:23 - ERROR] - pyrogram.dispatcher - 'Message' object has no attribute 'msg'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\Apps\Python\Python310\lib\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 21, in __init__
    self.msg._flags = {}
AttributeError: 'Message' object has no attribute 'msg'
[22-May-22 18:41:45 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:41:45 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:41:48 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:41:49 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:41:49 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:42:01 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:42:04 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:42:04 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:43:09 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:43:09 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:43:13 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:43:13 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:43:13 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:43:33 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:43:33 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:43:33 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:43:44 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:43:44 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:43:44 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:43:55 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:43:57 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:43:58 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:45:02 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:45:03 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:45:10 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:45:10 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:45:10 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:45:19 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:45:22 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:45:23 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:47:07 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:47:07 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:47:11 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:47:12 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:47:12 - INFO] - venom.core.client - ### Starting bot ###
